//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CapaEntidades
{
    using System;
    using System.Collections.Generic;
    
    public partial class Reemplazos
    {
        public int IDreemplazo { get; set; }
        public decimal TotalReemplazo { get; set; }
        public decimal IVAReemplazo { get; set; }
        public int IDdevolucion { get; set; }
    
        public virtual Devoluciones Devoluciones { get; set; }
    }
}
