//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CapaEntidades
{
    using System;
    using System.Collections.Generic;
    
    public partial class Ventas
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Ventas()
        {
            this.Creditos = new HashSet<Creditos>();
            this.DetalleFactura = new HashSet<DetalleFactura>();
        }
    
        public int IDFactura { get; set; }
        public System.DateTime FechaFactura { get; set; }
        public decimal EfectivoCliente { get; set; }
        public decimal TotalFactura { get; set; }
        public decimal TotalCambio { get; set; }
        public decimal IVAFactura { get; set; }
        public string tipoPago { get; set; }
        public string CedulaCliente { get; set; }
        public string CedulaEmpleado { get; set; }
    
        public virtual Clientes Clientes { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Creditos> Creditos { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DetalleFactura> DetalleFactura { get; set; }
        public virtual Empleados Empleados { get; set; }
    }
}
